CREATE TABLE IF NOT EXISTS hcpcs_raw (
  version        VARCHAR(16) NOT NULL,        -- e.g., '2025-10' for Oct 2025 release
  hcpc           VARCHAR(10) NOT NULL,
  seqnum         VARCHAR(8)  NULL,
  recid          VARCHAR(8)  NULL,
  long_desc      TEXT        NULL,
  short_desc     VARCHAR(255) NULL,
  price1         DECIMAL(12,2) NULL,
  price2         DECIMAL(12,2) NULL,
  price3         DECIMAL(12,2) NULL,
  price4         DECIMAL(12,2) NULL,
  mult_pi        VARCHAR(8)  NULL,
  cim1           VARCHAR(16) NULL, cim2 VARCHAR(16) NULL, cim3 VARCHAR(16) NULL,
  mcm1           VARCHAR(16) NULL, mcm2 VARCHAR(16) NULL, mcm3 VARCHAR(16) NULL,
  statute        VARCHAR(64) NULL,
  labcert1       VARCHAR(8)  NULL, labcert2 VARCHAR(8)  NULL, labcert3 VARCHAR(8)  NULL, labcert4 VARCHAR(8)  NULL,
  labcert5       VARCHAR(8)  NULL, labcert6 VARCHAR(8)  NULL, labcert7 VARCHAR(8)  NULL, labcert8 VARCHAR(8)  NULL,
  xref1          VARCHAR(10) NULL, xref2 VARCHAR(10) NULL, xref3 VARCHAR(10) NULL, xref4 VARCHAR(10) NULL, xref5 VARCHAR(10) NULL,
  cov            VARCHAR(8)  NULL,
  asc_grp        VARCHAR(16) NULL,
  asc_dt         DATE        NULL,
  opps           VARCHAR(32) NULL,
  opps_pi        VARCHAR(8)  NULL,
  opps_dt        DATE        NULL,
  procnote       VARCHAR(64) NULL,
  betos          VARCHAR(8)  NULL,
  tos1           VARCHAR(8)  NULL, tos2 VARCHAR(8) NULL, tos3 VARCHAR(8) NULL, tos4 VARCHAR(8) NULL, tos5 VARCHAR(8) NULL,
  anest_bu       DECIMAL(6,2) NULL,
  add_dt         DATE        NULL,
  act_eff_dt     DATE        NULL,
  term_dt        DATE        NULL,
  action_cd      VARCHAR(4)  NULL,
  loaded_at      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (version, hcpc)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;